### ISSUE TITLE
Parse additional custom metadata from encryption.xml, expose via generic name/value API?

### ISSUE THREAD

**Issue by danielweck** [readium/readium-sdk#162]
This can be used to store additional information in encryption.xml to about the size of the optionally-compressed + encrypted media assets, block size, etc.

https://github.com/readium/readium-sdk/blob/develop/ePub3/ePub/container.cpp#L271

https://github.com/readium/readium-sdk/blob/develop/ePub3/ePub/encryption.cpp#L26
https://github.com/readium/readium-sdk/blob/develop/ePub3/ePub/encryption.h#L45

**Comment by danielweck** [comment]
Specification:
http://www.idpf.org/epub/301/spec/epub-ocf.html#sec-container-metainf-encryption.xml

**Comment by danielweck** [comment]
Here's what this could look like (see the `enc:EncryptionProperty` custom XML content model):

```
<?xml version="1.0" encoding="UTF-8"?>

<encryption xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
	<enc:EncryptedData xmlns:enc="http://www.w3.org/2001/04/xmlenc#">
		<enc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
		<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
			<ds:RetrievalMethod URI="#yyy" Type="http://www.w3.org/2001/04/xmlenc#EncryptedKey"/>
		</ds:KeyInfo>
		<enc:CipherData>
			<enc:CipherReference URI="EPUB/audio/zzz.mp4"/>
		</enc:CipherData>
		<enc:EncryptionProperties>
			<enc:EncryptionProperty xmlns:ep="http://example.org/drm#encProp">
				<ep:compression method="8" sourceSize="6397902"/>
				<ep:largeContent sliceBlockSize="5120"/>
			</enc:EncryptionProperty>
		</enc:EncryptionProperties>
	</enc:EncryptedData>
	<enc:EncryptedKey xmlns:enc="http://www.w3.org/2001/04/xmlenc#" Id="yyy">
		<enc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p"/>
		<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
			<ds:KeyName>xxx</ds:KeyName>
		</ds:KeyInfo>
		<enc:CipherData>
			<enc:CipherValue>xxx</enc:CipherValue>
		</enc:CipherData>
	</enc:EncryptedKey>
</encryption>
```

**Comment by nleme** [comment]
Let me add a little bit more data to this issue, just to make clear what is the motivation behind this issue.

The central problem in this issue is the following. Currently, encryption.xml contains only one piece of information, which is the algorithm for encryption. Not only that, but that algorithm must be expressed as one of the identifiers defined by the W3C, which all correspond to URIs (for more details, please take a look at http://www.w3.org/TR/xmlsec-algorithms/). That spec had well defined URIs for font obfuscation, which was the main concern at the time that the ePUB3 spec was written by the IDPF. So, at that time, things worked quite well for font obfuscation.

However, as we moved on to use DRM on ePUB3 books, it became clear that solely the algorithm, and, on top of it, solely the algorithms defined by the W3C, would not be enough to identify specific DRM schemes.

Let me give an example, to make things more clear. Let's suppose that Adobe implements its DRM protection scheme in Readium. It creates the required ContentFilter classes to decrypt Adobe DRM protected content. However, Adobe DRM scheme encrypts the books using AES-128, so the encryption.xml file would solely contain the "algorithm" field with the value of:

http://www.w3.org/2001/04/xmlenc#aes128-cbc

Now, let's switch to the LCP DRM scheme. Let's suppose that ContentFilter classes for LCP are created as well. Notice, though, that the LCP DRM scheme also encrypts books using AES-128, therefore encryption.xml, again, would solely contain an "algorithm" field which would have the value of:

http://www.w3.org/2001/04/xmlenc#aes128-cbc

Therefore, based on the information given in encryption.xml, the Readium SDK would not be able to decide if a given book was encrypted using the Adobe scheme or the LCP scheme, and which ContentFilter objects it should instantiate.

Therefore, this issue was created to ask for more data to be included in encryption.xml. The objective is that, by adding more data to encryption.xml (maybe in the fashion suggested by Daniel above) the Readium SDK will be able to make the distinction between Adobe DRM protected books and LCP DRM protected books, and instantiate the correct ContentFilter objects.

**Comment by AlanQuatermain** [comment]
The XML-ENC specification allows for new algorithms and suchlike— that’s the reason it uses URIs as identifiers. The original LCP spec I wrote up made use of that by specifying a custom algorithm. The reader, if it recognized the algorithm URI, would then pull additional data from another file placed within META-INF by the LCP encryption module.

I’m not at all sure how much of that actually survived the working group process, however.

So, specifically, the idea is to define and specify algorithm URIs for LCP and (presumably) Adobe DRM’s encryption. They may be using AES-128 at the core, but the application of the cipher to the data (or the means of generating the key, etc.) are different enough that they can be considered to be new algorithms.

Alternatively, there’s plenty of room to keep the encryption algorithm the same and use the key description fields of XML-DSig or XML-ENC to describe the different key types, and/or the algorithms used to generate the keys. In the case of proprietary DRM, this would again likely be a custom URI. Again, the original LCP document specified a number of ways to generate keys, including a user-input type. I dimly recall that all the signing and encryption items can contain multiple children, thus defining multiple-pass encryption/signature/keygen schemes, which may be useful if you’re aiming to keep to the types specified directly by XML-ENC/DSig, for example.

**Comment by danielweck** [comment]
See in-progress @drminside PR: https://github.com/readium/readium-sdk/pull/216/files#diff-2a91bceb528aa605248d7eea4c1d946f
`enc:EncryptionProperties/enc:EncryptionProperty/ep:compression/@method`
and
`enc:EncryptionProperties/enc:EncryptionProperty/ep:compression/@sourceSize`

**Comment by danielweck** [comment]
?See also: https://github.com/IDPF/epub-revision/issues/57

**Comment by danielweck** [comment]
Follow-up on code already-merged to develop:
https://github.com/readium/readium-sdk/pull/219/files#r49749495

**Comment by danielweck** [comment]
See IDPF EPUB3 issue: https://github.com/IDPF/epub-revision/issues/646

**Comment by danielweck** [comment]
Regarding the Compression XML element namespace, @mattgarrish says that it's either `http://www.idpf.org/2016/encryption#compression` (to follow existing conventions) or `http://www.idpf.org/ns/encryption#compression` (new non-dated URI convention)

**Comment by danielweck** [comment]
Agreed on `http://www.idpf.org/2016/encryption#compression`
See: http://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-ocf.html#sec-enc-compression

**Comment by danielweck** [comment]
Fixed:
https://github.com/readium/readium-sdk/commit/a466b901bafd73ec9483d66e6088983f36161534

**Comment by danielweck** [comment]
Note that LCP-Server needs updating too: https://github.com/readium/readium-lcp-server/issues/24#issuecomment-225594254
