### ISSUE TITLE
XML parsing still goes to external websites for some DTDs

### ISSUE THREAD

**Issue by nleme** [readium/readium-sdk#234]
Recently at Bluefire we discovered that the XML parsing in the Readium SDK, done by libxml2, is still going to external websites to retrieve some DTDs. That is a problem because some of those websites can be very slow to respond, and that has bad consequences for the performance of the Readium SDK.

To be more specific, we found one book that contains XML that makes libxml2 query a server that takes 20 seconds to answer, which is really bad performance to open a book.

Apparently, this was fixed before, but this problem surfaced again, therefore we should find a way to solve it for good.

**Comment by rkwright** [comment]
Here is a link to the EPUB spec which declares that any external XML link is not allowed (though video and audio content are now excepted from this rule).

http://www.idpf.org/epub/301/spec/epub-publications.html#sec-xml-constraints

**Comment by danielweck** [comment]
This was fixed 7 months ago:

https://github.com/readium/readium-sdk/commit/9744784d828030284c7a03e9a688354bcc12515c

(well, apparently not)

const int ArchiveXmlReader::DEFAULT_OPTIONS = XML_PARSE_RECOVER | XML_PARSE_NOENT | XML_PARSE_DTDATTR | XML_PARSE_NONET;

**Comment by danielweck** [comment]
cc @mmenu-mantano

**Comment by rkwright** [comment]
Hm. I wonder if there are other performance issues related to this?  I.e badly authored EPUBs that inadvertently access DTDs (or other external resources) that are not so inaccessible so we don't really notice a BIG problem.

**Comment by nleme** [comment]
This turned out to be a red herring. The problem is this, which is actually a problem that may affect more people using the Readium SDK (maybe we should talk about this in the next meeting?...)

So, it just happens that, in addition to the Readium SDK code, there is also proprietary code that we use that we want to keep it just for us. As such, we cannot simply make a submodule of the Readium SDK (public repository) and use that. We actually use a private repository, that takes the Readium SDK code, plus some extra code that is our proprietary code.

It just so happens that, in this case, somehow we had fallen behind. The Readium SDK code in our repository did not have the fix to include the XML_PARSE_NONET flag, hence why we were seeing this problem.

This tells us that we need to do a better job keeping our code more up to date with the latest Readium SDK code.

Anyways, I'm sure that this is a problem that many other companies face, so this should be something that we need to make people aware of. As in: the Readium SDK code is code that it is still changing (for example, the latest changes to support Android Studio) so people using the Readium SDK should make sure to always get the latest code whenever possible.

**Comment by whmccoy** [comment]
I agree this is something we should communicate more emphatically about,
although of course the situation is common to all open source projects
especially when they are still rapidly evolving.

But Nelson, I wonder if there is more to this than meets the eye. Bluefire
has been a very active contributor so to hear that you guys didn't get a
change that's been in for 7 months makes me scratch my head. Was it that
for some reasons your proprietary code included modifications to the module
ePub3/ePub/archive_xml.cpp which later got that fix?  Is your proprietary
code bug  incremental features? Because if so, I would hope the
architecture and organization of Readium SDK wouldn't make it hard to
organize things so as to make it easy to stay current on new SDK builds
while still maintaining your own features (i.e. wouldn't require changes
within existing modules, for example, that would require more complex
ongoing merging).

Of course the best solution is to convince conributors that keeping changes
"proprietary" - especially if they are in the way of bug fixes or
incremental improvement - isn't the best way to go. If there's a pain in
keeping such fixes/improvements proprietary that's in some ways a positive
force for the collective good. But again it's been my understanding that
Bluefire has been generous in contributing back fixes and improvements so
I'm wondering what's up. And for sure adopters should be able to
conveniently keep major new features and other value-add (that may not even
make sense to contribute) private indefinitely.

--Bill

**Comment by nleme** [comment]
Hi Bill,

I very much agree with what you're saying, but let me give my two cents in this conversation (which, by the way, is a very good conversation for Readium overall).

In the specific case of archive_xml, I think that we just missed that specific change somehow. I didn't have the time to do an extensive post-mortem on how this happened. However, if it is somewhat surprising to me because we didn't put any proprietary code in that specific part of the code. After all, archive_xml is just a good way to encapsulate the code to parse the XML files, there is nothing particularly special about this part of the code that would require proprietary code there (and we ourselves didn't put any proprietary code there). And, more than anything, we have been trying to stick to the "standard" Readium SDK as much as possible.

Having said that, though, there is still some need for proprietary code in the Readium SDK. We have been trying to minimize that need, in order to be as close as possible to the mainline Readium SDK, and avoid issues just like that. However, I know at least of one part of the Readium SDK that requires a little bit of proprietary code, which is the ContentFilter classes.

As you may know, the ContentFilter classes are the way to deal with a number of things when the Readium SDK is reading an ePub file, including encryption. So, if you use any form of proprietary encryption, then you will have to add your own ContentFilter class that takes care of that. The way that the Readium SDK is architected, currently, the amount of common files that need to be changed for that is pretty small. We are talking about stuff like the project files for Xcode (or Android Studio), some of the initialization code files (because the encryption ContentFilter classes need to be registered) and maybe some other little changes.

We could, perhaps, modify the current architecture of the Readium SDK to become something more "plug and play" when it comes to ContentFilter code. For example (and just as an example), you could just drop a binary library and the Readium SDK code would automatically pick up that binary library and use any ContentFilter class that is available there. This way, people could use the Readium SDK with no change whatsoever to deal with proprietary encryption, for example.

If it is worth implementing that new architecture is a good question. Myself, I honestly haven't thought if it is worth or not. In any case, we can always talk some more about that. :-)

**Comment by whmccoy** [comment]
Hi Nelson, well I have to defer re:  the technical costs and benefits but
will  observe that if a very diligent contributor like Bluefire had issues
in integration due to needing to modify ContentFilter I think that other
adopters are highly like to similarly encounter problems. While there are
only a handful of off-the-shelf DRM systems and once they are
pre-integrated with Readium SDK few adopters should need to muck around
there, other adopters implement "silos" of their own DRM and so I could see
this still being a problem. But, again, I have no sense of the tradeoffs so
I'm just suggesting, in a vacuum, that the current situation doesn't seem
ideal thus if the cost to fix were modest, it would seem superficially
worthwhile. More generally, speaking if you have to modify the core of an
SDK to use it, it's not quite realizing the promise one expects from an
"SDK". At least, I would urge that we make it so that if one is using any
of the 3 interoperable DRMs (Adobe, Sony, LCP) that the ContentFilter code
needed is already there "off the shelf". If implementing a special DRM silo
is a bit harder, well that's not necessarily entirely bad.

Thanks for your clariifcations BTW...

--BIll

**Comment by bluefirepatrick** [comment]
Hi Bill,

The proprietary parts of the SDK we use for decryption, etc. do not conflict with keeping our repositories in sync with Readium.  We just happen to be using a version of the SDK that had been tweaked by a particular DRM vendor and that branch has not been updated.  (We are sometimes hesitant to monkey around with the repos after we get important things like that working)

It will be worth taking a look at how we can make a DRM vendor's ContentFilters more plug-n-play (I believe that allowing the RS to identify the flavor of DRM by the contents of encryption.xml is not quite 'standardized' and that some solutions may take it upon themselves to decide if they are needed.  But I also think that as the LCP code becomes more publicly available we can take a look at where the common ground for vendor-specific metadata may be.  

I'll add the caveat that the above is my general impression and that things may be further along then I remember them.

**Comment by danielweck** [comment]
CC@llemeurfr @HadrienGardeur 
Hello Patrick, it is my understanding that there is currently no standardized / interoperable mechanism for a reading system to identify DRM brand, flavour, profile, etc. (see https://github.com/IDPF/epub-revision/issues/575 ) The IDPF / EPUB `encryption.xml` format encodes per-resource crypto characteristics, but does not provide high-level / publication-wide DRM metadata, pretty much as defined by the parent W3C-Enc specification (modulo the recent proposed addition of EncryptionProperty>Compression, see
 https://github.com/readium/readium-sdk/issues/230 https://github.com/IDPF/epub-revision/issues/646 https://github.com/IDPF/epub-revision/issues/697).
For example, it may be possible to infer that LCP (Licensed Content Protection) "is used" by looking at `encryption.xml`'s `RetrievalMethod@URI` and `RetrievalMethod@Type` (by contrast, `EncryptionMethod@Algorithm` is generic / DRM-agnostic). However, this information is not sufficient for a reading system to determine that the encrypted EPUB conforms to the Readium LCP *ecosystem* (which requires processing a special certificate, secret key, etc.). That's why a reading system needs to fetch additional information from DRM-specific files, such as `license.lcpl` (which contains a machine-readable `profile` URI property, albeit without much in the way of human-readable descriptive metadata).
Dan

**Comment by rkwright** [comment]
Well, while I can understand that Bluefire is very busy, working hard to get their app out the door, I am very puzzled as to how this change in archive_xml was not picked up.  I assume that BF does periodic "pulls" (using whichever git approach they like) to synch their codebase with the current Readium codebase.
That said, we know very well that some of those who have cloned or forked Readium do NOT keep their codebase up to date or simply watch the commits and cherry-pick what they want.  IMHO, this is very unfortunate, but that is not my call.
My worry is that that is there might be some systematic problem, either in our repo structure, github or how they are used that leads to this problem.
