### ISSUE TITLE
Not able to build Readium SDK Master code on VS 2013

### ISSUE THREAD

**Issue by nrusta** [readium/readium-sdk#278]
Hi, I need to integrate Readium Reader component in C# windows application. For same I downloaded the Readium SDK from Master branch. I tried building the code under readium-sdk-master\Platform\Windows\ReadiumSDK folder but getting a lot of issues while building this code. Have copied issue log here. I tried taking help from Build & released document here (https://docs.google.com/document/d/1DphaTO2fu7mQoBKalzyfphIlOB2Ncp7yHbIbbti92CE/edit# ) but there Windows sections is empty. Please help.
![readiumissues](https://cloud.githubusercontent.com/assets/6264018/23791680/fb46f530-05a9-11e7-9ac9-bc785a9d95c8.PNG)

**Comment by rkwright** [comment]
@nrusta Neha,  Sorry, but the Windows code is woefully stale and largely unfinished.  This is because nobody has wanted to build anything with it.  I was the last one to do anything with it and that was as C++ and MFC (!) 2 years ago.  There WAS one company in Seattle (TagCreative) who apparently built something functional for Windows RT.  I personally never tried to build it or looked at it, but you might want to take a look since the code is still on [github](https://github.com/TagCreativeStudio). I would be more than willing to talk to you about it.  If you are interested, please contact me directly at rkwright@geofx.com

**Comment by rkwright** [comment]
Closing as outdated.  Never going to fix.
