### ISSUE TITLE
How To Get <ePub3/utilities/ref_counted.h> File

### ISSUE THREAD

**Issue by yangyii7913** [readium/readium-sdk#310]
When I compile the ReadiumSDK with VS2012, it shows that the "ePub3/utilities/ref_counted.h" file is needed, but, I can't find the file anywhere, how can I Get It?

**Comment by yangyii7913** [comment]
This is the error log,
[ePub3.log](https://github.com/readium/readium-sdk/files/1957369/ePub3.log)

**Comment by danielweck** [comment]
I am afraid Windows is in fact not fully supported / tested, due to lack of interest in the developer community (compared with iOS, Android, and to some extent OSX/MacOS as well).

I would recommend you take a look at these:

https://github.com/readium/readium-sdk/pull/192
https://github.com/readium/readium-sdk/issues/168
